# /// script
# requires-python = ">=3.11"
# dependencies = ["jellyfish"]
# ///
import json, random, re, sys
import jellyfish

sys.path.insert(0, "/Users/ammielyawson/work/tools/local-dictation-qwen/tools/accuracy-harness")
import ab_recorder as R
import ab_scored as S
import jargon_corpus as JC

def keys(s):
    return jellyfish.metaphone(re.sub(r"[^a-z0-9 ]", "", s.lower()))

vocab = {t.strip() for t in (R.VOCAB + ", " + S.EXTRA_VOCAB).split(",")} | set(JC._RARE_VOCAB)
extras = ["superbees", "lungchain", "choulet", "provalds", "qda", "paszk", "ginks",
          "open", "openai", "git hub", "long chain", "super base", "vessel", "versal",
          "cooper netties", "next js", "pineconen", "weaviate", "evreen", "clean-off",
          "knowledge", "night", "thumb", "psalm", "xylophone", "checkout", "check out",
          "wrangler", "she", "this", "match", "vue", "x", "ai", "brew", "cuda kernel",
          "whale", "what", "gnome", "pneumonia", "wrist", "aegis", "judge", "badge",
          "science", "ocean", "nation", "patio", "social", "vision", "casio", "hedge",
          "accept", "success", "occur", "lucky", "school", "ghost", "rough", "though",
          "yes", "gym", "quick", "zebra", "box", "exit", "xhosa", "away", "climb",
          "lamb", "combine", "chrome", "cache", "echo", "hedgehog", "sign", "signal"]
words = [w.strip() for w in open("/usr/share/dict/words") if 3 <= len(w.strip()) <= 12 and w.strip().isalpha()]
random.seed(42)
sample = random.sample(words, 150)
pairs = sorted({(w, keys(w)) for w in ([t for t in vocab if t] + extras + sample)})
lines = [f'    ("{a}", "{b}"),' for a, b in pairs]
body = "\n".join(lines)
print(f"""// GENERATED by gen_metaphone_swift.py — jellyfish (Rust) metaphone reference
// outputs for `Metaphone.key` conformance testing. Do not hand-edit.
let metaphoneFixture: [(String, String)] = [
{body}
]""")
