#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_NAME="LocalDictation"
APP_DIR="$PROJECT_DIR/$APP_NAME.app"
CONTENTS_DIR="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS_DIR/MacOS"
RESOURCES_DIR="$CONTENTS_DIR/Resources"
FRAMEWORKS_DIR="$CONTENTS_DIR/Frameworks"
HELPERS_DIR="$CONTENTS_DIR/Helpers"

SHORT_VERSION="${SHORT_VERSION:-0.1.0}"
BUILD_VERSION="$(git -C "$PROJECT_DIR" rev-list --count HEAD 2>/dev/null || echo 1)"

# Sparkle auto-update. SU_PUBLIC_ED_KEY pairs with the private EdDSA key in the
# keychain (generated by `generate_keys`); appcasts are signed with that key and
# verified against this one. SU_FEED_URL is the GitHub Releases latest-release
# permalink for the appcast (override via env when the repo/host differs).
SU_PUBLIC_ED_KEY="${SU_PUBLIC_ED_KEY:-pK8Z+wa903G8XYFRgt/oeYWXy+kOaFbAiMXl5yQ3/Ds=}"
SU_FEED_URL="${SU_FEED_URL:-https://github.com/AmmDuncan/local-dictation/releases/latest/download/appcast.xml}"

cd "$PROJECT_DIR"
swift build -c release --product LocalDictation

rm -rf "$APP_DIR"
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR" "$FRAMEWORKS_DIR" "$HELPERS_DIR"
cp "$PROJECT_DIR/.build/release/LocalDictation" "$MACOS_DIR/LocalDictation"
# Resolve bundled frameworks (Sparkle, etc.) from inside the .app.
install_name_tool -add_rpath @executable_path/../Frameworks "$MACOS_DIR/LocalDictation" 2>/dev/null || true

# App icon: regenerate the iconset → .icns, then bundle it.
rm -rf "$PROJECT_DIR/AppIcon.iconset"
swift "$PROJECT_DIR/scripts/make-icon.swift" "$PROJECT_DIR/AppIcon.iconset"
iconutil -c icns "$PROJECT_DIR/AppIcon.iconset" -o "$PROJECT_DIR/AppIcon.icns"
cp "$PROJECT_DIR/AppIcon.icns" "$RESOURCES_DIR/AppIcon.icns"

# Bundle the Silero VAD model so non-speech (silence/whistle/noise) is dropped
# instead of hallucinated into words.
VAD_SRC="$HOME/models/ggml-silero-v5.1.2.bin"
if [[ ! -f "$VAD_SRC" ]]; then
    curl -sL -o "$VAD_SRC" "https://huggingface.co/ggml-org/whisper-vad/resolve/main/ggml-silero-v5.1.2.bin" || true
fi
if [[ -f "$VAD_SRC" ]]; then
    cp "$VAD_SRC" "$RESOURCES_DIR/ggml-silero-v5.1.2.bin"
    echo "Bundled VAD model."
else
    echo "WARNING: VAD model not found — app runs without VAD."
fi

# Bundle whisper-cli + its Homebrew dylibs so friends need zero setup. We copy
# the binary into Helpers/, its three dylibs into Frameworks/, and rewrite every
# load path to @rpath so they resolve inside the .app instead of /opt/homebrew.
bundle_whisper() {
    local cli
    cli="$(command -v whisper-cli || true)"
    if [[ -z "$cli" ]]; then
        echo "WARNING: whisper-cli not found — app will rely on a system install at runtime."
        return
    fi
    cli="$(readlink -f "$cli" 2>/dev/null || python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$cli")"
    cp "$cli" "$HELPERS_DIR/whisper-cli"
    chmod +x "$HELPERS_DIR/whisper-cli"

    local dylibs=(libwhisper.1.dylib libggml.0.dylib libggml-base.0.dylib)
    for name in "${dylibs[@]}"; do
        local src
        src="$(find /opt/homebrew -name "$name" 2>/dev/null | head -1)"
        [[ -z "$src" ]] && { echo "WARNING: $name not found; whisper bundling incomplete."; return; }
        cp -L "$src" "$FRAMEWORKS_DIR/$name"
        chmod +w "$FRAMEWORKS_DIR/$name"
    done

    # whisper-cli: point ggml deps at @rpath, add a path to Frameworks.
    install_name_tool \
        -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
        -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
        -add_rpath @executable_path/../Frameworks \
        "$HELPERS_DIR/whisper-cli"

    # whisper-server: same deps, keeps the model resident across dictations.
    local srv
    srv="$(command -v whisper-server || true)"
    if [[ -n "$srv" ]]; then
        srv="$(readlink -f "$srv" 2>/dev/null || python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$srv")"
        cp "$srv" "$HELPERS_DIR/whisper-server"; chmod +x "$HELPERS_DIR/whisper-server"
        install_name_tool \
            -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
            -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
            -add_rpath @executable_path/../Frameworks \
            "$HELPERS_DIR/whisper-server"
    fi

    # Each dylib: set its own id to @rpath, repoint inter-deps, and add @loader_path
    # so sibling dylibs in Frameworks/ resolve.
    install_name_tool -id @rpath/libwhisper.1.dylib \
        -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
        -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
        -add_rpath @loader_path "$FRAMEWORKS_DIR/libwhisper.1.dylib"
    install_name_tool -id @rpath/libggml.0.dylib \
        -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
        -add_rpath @loader_path "$FRAMEWORKS_DIR/libggml.0.dylib"
    install_name_tool -id @rpath/libggml-base.0.dylib \
        -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
        -change /opt/homebrew/opt/libomp/lib/libomp.dylib @rpath/libomp.dylib \
        "$FRAMEWORKS_DIR/libggml-base.0.dylib"

    # ggml's compute backends (Metal/CPU/BLAS) are dlopen'd PLUGINS loaded from a
    # path baked into libggml.0.dylib (Homebrew's libexec). Bundle the plugins +
    # libomp, then patch that baked path to a fixed location the app symlinks to
    # its own Frameworks at runtime (LD_GGML_BACKENDS_LINK below + WhisperLocator).
    local libomp
    libomp="$(find /opt/homebrew -name libomp.dylib 2>/dev/null | head -1)"
    if [[ -n "$libomp" ]]; then
        cp -L "$libomp" "$FRAMEWORKS_DIR/libomp.dylib"; chmod +w "$FRAMEWORKS_DIR/libomp.dylib"
        install_name_tool -id @rpath/libomp.dylib "$FRAMEWORKS_DIR/libomp.dylib"
    fi

    local baked
    baked="$(strings "$FRAMEWORKS_DIR/libggml.0.dylib" | grep -oE '/opt/homebrew/Cellar/ggml/[0-9.]+/libexec' | head -1)"
    if [[ -n "$baked" && -d "$baked" ]]; then
        for plugin in "$baked"/libggml-*.so; do
            local pn; pn="$(basename "$plugin")"
            cp -L "$plugin" "$FRAMEWORKS_DIR/$pn"; chmod +w "$FRAMEWORKS_DIR/$pn"
            install_name_tool \
                -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
                -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
                -change /opt/homebrew/opt/libomp/lib/libomp.dylib @rpath/libomp.dylib \
                -add_rpath @loader_path "$FRAMEWORKS_DIR/$pn" 2>/dev/null || true
        done
        python3 - "$FRAMEWORKS_DIR/libggml.0.dylib" "$baked" "$LD_GGML_BACKENDS_LINK" <<'PYEOF'
import sys
f, old, new = sys.argv[1], sys.argv[2].encode(), sys.argv[3].encode()
if len(new) != len(old):
    sys.exit(f"FATAL: LD_GGML_BACKENDS_LINK must be {len(old)} bytes (to match '{old.decode()}'), got {len(new)}. Adjust it and WhisperLocator.backendsLinkPath together.")
data = open(f, 'rb').read()
if old not in data:
    sys.exit(f"FATAL: baked ggml path {old.decode()} not found in libggml")
open(f, 'wb').write(data.replace(old, new))
print(f"patched ggml backend path: {old.decode()} -> {new.decode()}")
PYEOF
    fi

    echo "Bundled whisper-cli + dylibs + backend plugins."
}
# Must be EXACTLY the same length + value as WhisperLocator.backendsLinkPath.
LD_GGML_BACKENDS_LINK="/tmp/local-dictation-ggml-backends-dir01"
bundle_whisper

# Bundle llama-server + its dylibs for the optional on-device LLM polish pass so
# friends get polish (now relied on for meaning-based punctuation) with zero
# setup. ggml + its backend plugins are SHARED with whisper — same
# /opt/homebrew/opt/ggml/libggml.0.dylib, already bundled and baked-path-patched
# by bundle_whisper — so we only add llama's own dylibs plus openssl (llama-server
# links it for HF downloads we don't use, but it must resolve at load time).
# Must run AFTER bundle_whisper so the shared ggml dylibs already sit in Frameworks/.
bundle_llama() {
    local srv
    srv="$(command -v llama-server || true)"
    if [[ -z "$srv" ]]; then
        echo "WARNING: llama-server not found — LLM polish stays Homebrew-only (off for friends)."
        return
    fi
    if [[ ! -f "$FRAMEWORKS_DIR/libggml.0.dylib" ]]; then
        echo "WARNING: shared libggml not bundled (whisper bundling failed?) — skipping llama; polish backend would not resolve."
        return
    fi
    srv="$(readlink -f "$srv" 2>/dev/null || python3 -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "$srv")"
    cp "$srv" "$HELPERS_DIR/llama-server"; chmod +x "$HELPERS_DIR/llama-server"

    local libdir
    libdir="$(cd "$(dirname "$srv")/../lib" && pwd)"

    # llama's own dylibs (cp -L resolves the version symlinks, keeps the @rpath soname).
    local llama_dylibs=(libllama.0.dylib libllama-common.0.dylib libmtmd.0.dylib libllama-server-impl.dylib)
    for name in "${llama_dylibs[@]}"; do
        if [[ ! -f "$libdir/$name" ]]; then
            echo "WARNING: $name not found in $libdir; llama bundling incomplete."; return
        fi
        cp -L "$libdir/$name" "$FRAMEWORKS_DIR/$name"; chmod +w "$FRAMEWORKS_DIR/$name"
    done

    # openssl (resolve the opt symlink → real Cellar files).
    local ssl_dir="/opt/homebrew/opt/openssl@3/lib"
    for name in libssl.3.dylib libcrypto.3.dylib; do
        if [[ ! -f "$ssl_dir/$name" ]]; then
            echo "WARNING: $name not found; llama bundling incomplete."; return
        fi
        cp -L "$ssl_dir/$name" "$FRAMEWORKS_DIR/$name"; chmod +w "$FRAMEWORKS_DIR/$name"
    done
    # libssl references libcrypto by its versioned Cellar path — capture it for -change.
    local ssl_crypto_ref
    ssl_crypto_ref="$(otool -L "$FRAMEWORKS_DIR/libssl.3.dylib" | grep -oE '/opt/homebrew/(opt/openssl@3|Cellar/openssl@3/[0-9._]+)/lib/libcrypto.3.dylib' | head -1)"

    # llama-server: repoint abs ggml/openssl deps to @rpath; its @rpath/libllama*
    # deps resolve via the new Frameworks rpath. ggml backends come from the shared,
    # already-patched libggml + the /tmp symlink (LlamaServerManager.ensureBackendsLinked).
    install_name_tool \
        -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
        -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
        -change /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib @rpath/libssl.3.dylib \
        -change /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib @rpath/libcrypto.3.dylib \
        -add_rpath @executable_path/../Frameworks \
        "$HELPERS_DIR/llama-server"

    # Each llama dylib: id to @rpath, repoint abs ggml/openssl deps, add @loader_path
    # so sibling dylibs in Frameworks/ resolve. (Inter-llama deps are already @rpath.)
    for name in "${llama_dylibs[@]}"; do
        install_name_tool -id "@rpath/$name" \
            -change /opt/homebrew/opt/ggml/lib/libggml.0.dylib @rpath/libggml.0.dylib \
            -change /opt/homebrew/opt/ggml/lib/libggml-base.0.dylib @rpath/libggml-base.0.dylib \
            -change /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib @rpath/libssl.3.dylib \
            -change /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib @rpath/libcrypto.3.dylib \
            -add_rpath @loader_path "$FRAMEWORKS_DIR/$name" 2>/dev/null || true
    done

    # openssl: own ids to @rpath; libssl points at the bundled libcrypto.
    install_name_tool -id @rpath/libcrypto.3.dylib "$FRAMEWORKS_DIR/libcrypto.3.dylib"
    install_name_tool -id @rpath/libssl.3.dylib \
        ${ssl_crypto_ref:+-change "$ssl_crypto_ref" @rpath/libcrypto.3.dylib} \
        -add_rpath @loader_path "$FRAMEWORKS_DIR/libssl.3.dylib"

    echo "Bundled llama-server + dylibs (LLM polish, ggml shared with whisper)."
}
bundle_llama

# Bundle Sparkle.framework for in-app auto-update. The universal slice from the
# resolved xcframework goes into Frameworks/; the main binary's rpath (above)
# resolves it. Nested helpers (Autoupdate, Updater.app, XPCServices) are signed
# below before the bundle-wide signature.
bundle_sparkle() {
    local fw
    fw="$(find "$PROJECT_DIR/.build/artifacts" -path "*Sparkle.xcframework/macos-arm64_x86_64/Sparkle.framework" -type d 2>/dev/null | head -1)"
    if [[ -z "$fw" ]]; then
        echo "WARNING: Sparkle.framework not found — auto-update disabled in this build."
        return
    fi
    cp -R "$fw" "$FRAMEWORKS_DIR/Sparkle.framework"
    echo "Bundled Sparkle.framework."
}
bundle_sparkle

cat > "$CONTENTS_DIR/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>LocalDictation</string>
  <key>CFBundleIdentifier</key>
  <string>dev.ammiel.local-dictation</string>
  <key>CFBundleIconFile</key>
  <string>AppIcon</string>
  <key>CFBundleIconName</key>
  <string>AppIcon</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>Local Dictation</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>${SHORT_VERSION}</string>
  <key>CFBundleVersion</key>
  <string>${BUILD_VERSION}</string>
  <key>LSMinimumSystemVersion</key>
  <string>14.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSMicrophoneUsageDescription</key>
  <string>Local Dictation records your voice to transcribe it locally with whisper.cpp.</string>
  <key>SUFeedURL</key>
  <string>${SU_FEED_URL}</string>
  <key>SUPublicEDKey</key>
  <string>${SU_PUBLIC_ED_KEY}</string>
  <key>SUEnableAutomaticChecks</key>
  <true/>
  <key>SUScheduledCheckInterval</key>
  <integer>86400</integer>
</dict>
</plist>
PLIST

# Sign nested binaries first, then the app bundle (deep). Adding the icon, the
# Info.plist, and the bundled binaries after `swift build` invalidates the
# original signature, so we re-sign everything last. The stable self-signed
# identity (scripts/setup-signing.sh) keeps Microphone/Accessibility grants
# across rebuilds; ad-hoc is the fallback (resets permissions each build).
SIGN_IDENTITY="Local Dictation Dev"
if security find-identity -v -p codesigning | grep -q "$SIGN_IDENTITY"; then
    SIGN_AS="$SIGN_IDENTITY"
    echo "Signing with stable identity: $SIGN_IDENTITY"
else
    SIGN_AS="-"
    echo "WARNING: '$SIGN_IDENTITY' not found — signing ad-hoc. Run scripts/setup-signing.sh."
fi

for nested in "$FRAMEWORKS_DIR"/*.dylib "$FRAMEWORKS_DIR"/*.so "$HELPERS_DIR"/*; do
    [[ -e "$nested" ]] && codesign --force --sign "$SIGN_AS" "$nested"
done

# Sparkle's nested helpers must be signed inside-out before the bundle.
SP="$FRAMEWORKS_DIR/Sparkle.framework"
if [[ -d "$SP" ]]; then
    codesign --force --sign "$SIGN_AS" "$SP/Versions/B/XPCServices/Downloader.xpc" 2>/dev/null || true
    codesign --force --sign "$SIGN_AS" "$SP/Versions/B/XPCServices/Installer.xpc" 2>/dev/null || true
    codesign --force --sign "$SIGN_AS" "$SP/Versions/B/Autoupdate"
    codesign --force --deep --sign "$SIGN_AS" "$SP/Versions/B/Updater.app"
    codesign --force --sign "$SIGN_AS" "$SP"
fi

codesign --force --deep --sign "$SIGN_AS" "$APP_DIR"
codesign --verify --deep --strict "$APP_DIR" && echo "Signature OK"

echo "Built $APP_DIR (v$SHORT_VERSION build $BUILD_VERSION)"
